name: vavoo_app
on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install curl_cffi requests

      - name: Run Python Script
        run: |
          curl -L -o vavoo_app.py "${{ secrets.VAVOO_APP_URL }}"
          python vavoo_app.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f vavoo_app.m3u8 ]; then
            git add vavoo_app.m3u8
            git diff --staged --quiet || (git commit -m "üîÑ Otomatik G√ºncelleme" && git push)
          else
            echo "‚ö†Ô∏è vavoo_app.m3u8 bulunamadƒ±!"
            exit 1
          fi
          
